# Question no.1... 
# values for probability...
p_rain_chance = 0.3
p_umbrella_order_arrive_on_time = 0.4

# define formula...
p_chance_of_umbrella_arrive_on_time = (p_rain_chance * p_umbrella_order_arrive_on_time)

# printp_chance_of_umbrella_arrive_on_time...
print(p_chance_of_umbrella_arrive_on_time)

# Question no.2... 
# values for probability...
p_rain_chance = 0.3
p_umbrella_order_arrive_on_time = 0.4

# define formula...
p_chance_of_no_umbrella_arrive = (1 - p_rain_chance) + 0.4  - (p_rain_chance * p_umbrella_order_arrive_on_time)

# print p_chance_of_no_umbrella_arrive...
print(p_chance_of_no_umbrella_arrive)

# Question no.3... 
# values for probability...
p_rain_chance = 0.3
p_umbrella_arrive_chances_knows = 0.2

# define formula...
p_of_umbrella_arrive_on_time = (p_rain_chance * p_umbrella_arrive_chances_knows)

# print p_chance_of_umbrella_arrive...
print(p_of_umbrella_arrive_on_time)

# Question no.4...
# import binom from scipy.syats...
from scipy.stats import binom

# number of trails...
n = 137

# number of probability...
p = 0.40

p_50_or_more_noshows = 0.0

for x in range(50, 138):
    p_50_or_more_noshows += binom.pmf(x, n, p)
    
print(p_50_or_more_noshows)

# Question no.5... 
# import beta a from scipy.stats
from scipy.stats import beta

# number of heads...
heads = 8

# number of tails...
tails = 2

# define formula...
p = 1.0 - beta.cdf(0.5, heads, tails)

# print p...
print(p)